on:
  push:
    tags:
    - 'v*'

name: Create Release

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install musl toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools
        rustup target add x86_64-unknown-linux-musl
    - name: Build static
      run: cargo build --release --target=x86_64-unknown-linux-musl

    - name: Stage asset
      run: cp target/x86_64-unknown-linux-musl/release/ssologin ssologin_linux

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ssologin_linux

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: build windows for release
      run: cargo build --verbose --release

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/ssologin.exe

  build_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: build mac for release
      run: cargo build --verbose --release

    - name: Stage asset
      run: cp target/release/ssologin ssologin_mac

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: ssologin_mac
